### ISSUE TITLE
More informative error pages

### ISSUE THREAD

**Issue by mrManner** [Scouterna/simplesamlphp-module-scouterna-theme#1]
From @junsve:
> Hej,
> Jag har påtalat det förut, felmeddelandet när jag med ScoutId försöker
> logga in på en site jag inte har behörighet är ful och hänvisar till en
> icke informationssida som inte beskriver problemet.
> / Sven

The message referred to above is the http 403 page from SimpleSamlPHP, that is shown when a user is blocked from a service by an Authproc filter in SSP. They should be possible to update in this theme.

**Comment by Klako** [comment]
Stängs av #3
